# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 673d3d306ea4dbfdb83fae9c88052389834e6826f08350d4ca95b2a15a0ce2c7f2f2fdd4219665b17b7ef150d984d3d112bbf466ad0af09a030e3ca55b03335d

test:
  secret_key_base: a59e63ce6f6810fdd0beab198686853373ede67111408c4fc20811792d62d7ef07d507c42475c82462220ce04a64bcf86d6926719a1d8d77f79f24418bb7c60b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
